quarkus.http.port=8082

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.rest-client.order-service.url=http://order-service:8081

# Serviço externo do professor
quarkus.rest-client.pagamento-externo.url=http://localhost:8089


# =========================
# CONSUMER - Pedido Criado
# =========================
mp.messaging.incoming.pedido-criado-in.connector=smallrye-kafka
mp.messaging.incoming.pedido-criado-in.topic=pedido.criado
mp.messaging.incoming.pedido-criado-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.pedido-criado-in.auto.offset.reset=earliest

# =========================
# PRODUCERS - Resultado do Pagamento
# =========================

# Pagamento aprovado
mp.messaging.outgoing.pagamento-aprovado-out.connector=smallrye-kafka
mp.messaging.outgoing.pagamento-aprovado-out.topic=pagamento.aprovado
mp.messaging.outgoing.pagamento-aprovado-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Pagamento pendente
mp.messaging.outgoing.pagamento-pendente-out.connector=smallrye-kafka
mp.messaging.outgoing.pagamento-pendente-out.topic=pagamento.pendente
mp.messaging.outgoing.pagamento-pendente-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

#Pagamento abandonado
mp.messaging.outgoing.pagamento-abandonado-out.connector=smallrye-kafka
mp.messaging.outgoing.pagamento-abandonado-out.topic=pagamento.abandonado
mp.messaging.outgoing.pagamento-abandonado-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.pagamento-pendente-in.connector=smallrye-kafka
mp.messaging.incoming.pagamento-pendente-in.topic=pagamento.pendente
mp.messaging.incoming.pagamento-pendente-in.group.id=payment-retry
mp.messaging.incoming.pagamento-pendente-in.auto.offset.reset=earliest

mp.messaging.incoming.pagamento-disponivel-in.connector=smallrye-kafka
mp.messaging.incoming.pagamento-disponivel-in.topic=pagamento.disponivel
mp.messaging.incoming.pagamento-disponivel-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Pagamento disponível (health UP)
mp.messaging.outgoing.pagamento-disponivel-out.connector=smallrye-kafka
mp.messaging.outgoing.pagamento-disponivel-out.topic=pagamento.disponivel
mp.messaging.outgoing.pagamento-disponivel-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer


