FROM eclipse-temurin:21-jre

WORKDIR /app

COPY build/quarkus-app/lib/ /app/lib/
COPY build/quarkus-app/*.jar /app/
COPY build/quarkus-app/app/ /app/app/
COPY build/quarkus-app/quarkus/ /app/quarkus/

EXPOSE 8082

CMD ["java", "-jar", "quarkus-run.jar"]