# =========================
# HTTP & KAFKA GLOBAL
# =========================
quarkus.http.port=8081
quarkus.http.host=0.0.0.0

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

security.jwt.secret=DEV_SECRET_FIXA_SUPER_FORTE_123456789

# ===============================
# DATASOURCE
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=order_user
quarkus.datasource.password=order_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/order_db

# ===============================
# FLYWAY
# ===============================
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# Hibernate N�O tenta criar sequence
quarkus.hibernate-orm.database.generation=none

# Opcional (debug)
quarkus.hibernate-orm.log.sql=false

# =========================
# PRODUCER - Pedido Criado
# =========================
mp.messaging.outgoing.pedido-criado-out.connector=smallrye-kafka
mp.messaging.outgoing.pedido-criado-out.topic=pedido.criado
mp.messaging.outgoing.pedido-criado-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# =========================
# CONSUMERS - Respostas do Pagamento
# =========================

# Pagamento aprovado
mp.messaging.incoming.pagamento-aprovado-in.connector=smallrye-kafka
mp.messaging.incoming.pagamento-aprovado-in.topic=pagamento.aprovado
mp.messaging.incoming.pagamento-aprovado-in.group.id=order-service
mp.messaging.incoming.pagamento-aprovado-in.auto.offset.reset=latest
mp.messaging.incoming.pagamento-aprovado-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Pagamento pendente (se realmente precisar consumir aqui)
mp.messaging.incoming.pagamento-pendente-in.connector=smallrye-kafka
mp.messaging.incoming.pagamento-pendente-in.topic=pagamento.pendente
mp.messaging.incoming.pagamento-pendente-in.group.id=order-service
mp.messaging.incoming.pagamento-pendente-in.auto.offset.reset=latest
mp.messaging.incoming.pagamento-pendente-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# =========================
# Pagamento abandonado
# =========================
mp.messaging.incoming.pagamento-abandonado-in.connector=smallrye-kafka
mp.messaging.incoming.pagamento-abandonado-in.topic=pagamento.abandonado
mp.messaging.incoming.pagamento-abandonado-in.group.id=order-service
mp.messaging.incoming.pagamento-abandonado-in.auto.offset.reset=latest
mp.messaging.incoming.pagamento-abandonado-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
