quarkus.http.port=8080

security.jwt.secret=DEV_SECRET_FIXA_SUPER_FORTE_123456789

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/identity

# Hibernate (NÃO cria schema)
#quarkus.hibernate-orm.persistence-unit.default.database.generation=validate
quarkus.hibernate-orm.log.sql=false

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
